const ActionTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_PRODUCT: "FETCH_PRODUCT",
  LOAD_USER: "LOAD_USER",
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT",
  SIGN_IN_ERROR: "SIGN_IN_ERROR",
  SIGN_UP: "SIGN_UP",
  SIGN_UP_ERROR: "SIGN_UP_ERROR",
  SET_ERROR: "SET_ERROR",
  IS_LOADING: "IS_LOADING",
  GET_CART: "GET_CART",
  PURCHASE: "PURCHASE",
  CLEAR_CART: "CLEAR_CART",
  JWT_EXPIRED: "JWT_EXPIRED"
};

export default ActionTypes;
