const ActionTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_PRODUCT: "FETCH_PRODUCT",
  LOAD_USER: "LOAD_USER",
  SIGN_IN: "SIGN_IN",
  SIGN_IN_ERROR: "SIGN_IN_ERROR",
  SET_ERROR: "SET_ERROR"
};

export default ActionTypes;
